final final

diff --git a/.github/workflows/build_test_deploy.yml b/.github/workflows/build_test_deploy.yml
--- a/.github/workflows/build_test_deploy.yml
+++ b/.github/workflows/build_test_deploy.yml
@@ -143,5 +143,25 @@ jobs:
            # Step 2: Modify the configuration to add the CNAME
            jq '.DistributionConfig.Aliases.Items = ["${{ env.DOMAIN_NAME }}"] | .DistributionConfig.Aliases.Quantity = 1 | .DistributionConfig' distribution-config.json > modified-config.json
 
-           # Step 3: Update the CloudFront distribution with the modified configuration
-           aws cloudfront update-distribution --id ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID_CNAME_ADD }} --if-match $(jq -r '.ETag' distribution-config.json) --distribution-config file://modified-config.json
+           # Step 3: Update the CloudFront distribution with the modified configuration in a loop
+            success=false
+            max_retries=600
+            counter=0
+            while [ $counter -lt $max_retries ]
+            do
+              if aws cloudfront update-distribution --id ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID_CNAME_ADD }} --if-match $(jq -r '.ETag' distribution-config.json) --distribution-config file://modified-config.json; then
+                success=true
+                break
+              else
+                echo "Attempt $((counter+1)) to add CNAME failed. Retrying in 1 second..."
+                sleep 1
+                counter=$((counter+1))
+              fi
+            done
+
+            if [ "$success" == "false" ]; then
+              echo "Failed to add CNAME after $max_retries attempts"
+              exit 1
+            else
+              echo "CNAME added successfully"
+            fi
